### ISSUE TITLE
Divvun products should have the same publisher

### ISSUE THREAD

**Issue by albbas** [divvun/divvun-manager-windows#19]
Our packages have different publisher names, they should be the same
![image](https://user-images.githubusercontent.com/75695/92923237-69956b00-f437-11ea-919d-323372b20c0c.png)

**Comment by bbqsrc** [comment]
This is an issue for each individual repository where the metadata is incorrect. That would be each of the keyboard repositories I imagine. We should use the Norwegian name as it is the name on the signing certificate.
