### ISSUE TITLE
Languages sorted on ISO code, not name

### ISSUE THREAD

**Issue by snomos** [divvun/divvun-manager-windows#24]
![image](https://user-images.githubusercontent.com/1255285/99942996-3ea18e80-2d79-11eb-8065-9bcab2959e0a.png)

This seems very random to users, most will not know the ISO code of any language. The mac version seems to sort on the display name:

![image](https://user-images.githubusercontent.com/1255285/99943097-6e509680-2d79-11eb-842a-42e71045dcdf.png)

which is arguably better.

**Comment by bbqsrc** [comment]
<img width="898" alt="image" src="https://user-images.githubusercontent.com/279099/133686670-9737687d-0a01-47c4-b287-8753bfb2b47d.png">

Fixed.
