### ISSUE TITLE
Får ikke åpnet programmet uten at det krasjer. 

### ISSUE THREAD

**Issue by ITKristoffer** [divvun/divvun-manager-windows#30]
Windows 10 Enterprise
Versjon 1709
OS-build: 16299.2166

Error Code: Windows.Web.UI.WebViewControlSettings

Lastet ned divvun og når vi åpner programmet så får vi feilmelding. 

Vi har prøvd å:
Reinstallere programmet
Kjøre som admin
Startet PCen på nytt
Installere på admin bruker

**Comment by ITKristoffer** [comment]
![Uploading feilmelding.jpg…]()

**Comment by ITKristoffer** [comment]
Datmaskin: HP Probook 440 G5.

**Comment by snomos** [comment]
Hei! Kan du lasta opp skjermbiletet av feilmeldinga ein gong til? Det ser ikkje ut til at det kom heilt fram.

**Comment by ITKristoffer** [comment]
![feilmelding](https://user-images.githubusercontent.com/78599257/107036930-af721780-67ba-11eb-9551-10386effd72b.jpg)

**Comment by snomos** [comment]
Takk, vi skal sjå på det.

**Comment by bbqsrc** [comment]
It's a known issue that has been fixed on the main branch and will be included in the the v2.2.0 release.

Some installations of Windows really _really_ hate the webview. We're replacing it with an embedded chromium. 😄

**Comment by ITKristoffer** [comment]
Ok, do you have an estimate for when v2.2.0 will be released?

**Comment by bbqsrc** [comment]
Oh yes, sorry, I forgot to add that. 2 weeks at most 😄

**Comment by ITKristoffer** [comment]
Ok, I will inform the users about the wait.
