### ISSUE TITLE
Oneclick installer removed english keyboard

### ISSUE THREAD

**Issue by albbas** [divvun/divvun-manager-windows#36]
English was enabled before I installed the North sami resources. After reboot, the english keyboard was replaced by the North sami one.

![image](https://user-images.githubusercontent.com/75695/114532082-c581d580-9c4c-11eb-89b4-f18ee0dc3c51.png)

**Comment by albbas** [comment]
The oneclick installer version is the same as in #35

**Comment by snomos** [comment]
This is also for @ZoeyR 😄

**Comment by ZoeyR** [comment]
I can't reproduce this on my end, but my guess is that something has damaged the registry (probably windows itself) so we didn't detect english as actually installed. I'll try and think about possible mitigations for that.
