### ISSUE TITLE
rmg (Traveller Norwegian) missing from DM list

### ISSUE THREAD

**Issue by Trondtr** [divvun/divvun-manager-windows#43]
Traveller Norwegian does not surface in the language list of the DM for either Mac or Windows). I thought the problem was technical and due to the rmg fst and thus made an issue under giellalt/lang-rmg.

It then struck me that the real difference between lang-rmg and the other ones is that it is our newest repository, only 13 days old. So perhaps it just hasn§t been added yet. I thus post the Issue here, in case people making the DM look here and not under lang-rmg.

The fix: Add Traveller Norwegian, rmg, to the list of spellcheckers to be installed in the Divvun Manager.

**Comment by Eijebong** [comment]
It was missing in the pahkat repository. This is now fixed and should appear in divvun-manager

![rmg](https://user-images.githubusercontent.com/3650385/158573655-1290a0a2-ebc4-4e31-b321-dddfbfc07882.png)

**Comment by snomos** [comment]
This also fixes https://github.com/giellalt/lang-rmg/issues/1.
