### ISSUE TITLE
DM **opens** instead of being **run as admin** when you confirms you want to use DM directly after installation

### ISSUE THREAD

**Issue by Trondtr** [divvun/divvun-manager-windows#61]
DM is not adjusted to Windows Computers where the user must use "Make me admin" or similar programs

What I did, and how it went:

1. I made sure I have used the Make me admin account, I have now admin rights
2. I fetched the installer, double clicks, and the installed program opens, offering me spellcheckers to install
3. I chose language
4. The program told me it must be run as an admin
5. I closed the program (not only its window!), right-click, avoided the "open" option and chose "run as administrator"
6. Now it worked

I was left with a feeling of being fooled in the first place. Why did the initial double click make me open the program instead of letting me running it as the admin I was (albeit in temporary feathers)?

**Comment by snomos** [comment]
Additional info:

> 1. I made sure I have used the *Make me admin* account, I have now admin rights

That is, the installation is done on a Windows 11 computer within a corporate setting, where regular users have limited rights in daily use (corporate security thing). One can elevate one's rights using a tool named as above, giving admin rights for a period of 15 minutes.

**Comment by snomos** [comment]
This is a "feature" of Windows, just don't check "Open after installation" if you want/need to run it as admin, and then start DM manually the way you desire.
